//import "./css/style.css";
import "./css/old.css";

import { Inter } from "next/font/google";

import Header from "@/components/ui/header";
import Banner from "@/components/banner";

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-inter",
    display: "swap",
});

export const metadata = {
    title: "ARWeb",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body
                className={`${inter.variable} font-inter antialiased bg-white text-gray-900 tracking-tight`}
            >
                <div className="Simpleflex flex-col min-h-screen overflow-hidden supports-[overflow:clip]:overflow-clip">
                    {/* <Header />
                        {children}
                        <Banner /> */}
                    <p>
                        Hey!
                        <br />
                        <br />
                        My portfolio is pretty outdated so i decided to take it
                        down for a while.
                        <br />
                        I'll work on a new one when i have the time.
                        <br />
                        <br />
                        If you're looking for my Cydia repository, go here:{" "}
                        <a href="https://arwebse.github.io">
                            arwebse.github.io
                        </a>
                    </p>
                </div>
            </body>
        </html>
    );
}
